artifact_uri: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/1ef5a49e2c4a4b5da2c3e1eea9c99b49/artifacts
end_time: 1743027426749
entry_point_name: ''
experiment_id: '419635633295998848'
lifecycle_stage: active
run_id: 1ef5a49e2c4a4b5da2c3e1eea9c99b49
run_name: youthful-worm-522
run_uuid: 1ef5a49e2c4a4b5da2c3e1eea9c99b49
source_name: ''
source_type: 4
source_version: ''
start_time: 1743027422018
status: 3
tags: []
user_id: Francy
