version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - app-data:/app/data
      - app-artifacts:/app/artifacts
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/mlflow.db
      - MLFLOW_TRACKING_URI=http://127.0.0.1:5001
    command: >
      sh -c "mlflow server --backend-store-uri sqlite:////app/data/mlflow.db
      --default-artifact-root /app/artifacts
      --host 0.0.0.0 --port 5001 & sleep 5 && python app.py"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /app/logs:/var/log/app  # Montrez le dossier de logs de votre app
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml

volumes:
  app-data:
  app-artifacts: