aliases: []
creation_timestamp: 1743075902651
current_stage: None
description: null
last_updated_timestamp: 1743075902651
name: Model_for_User_Feedback
run_id: 964dbe11c15941ee8e71bb003f614cac
run_link: null
source: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/964dbe11c15941ee8e71bb003f614cac/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/964dbe11c15941ee8e71bb003f614cac/artifacts/model
user_id: null
version: 8
