artifact_uri: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/edf2848a8fcb45e591568f56edadddc0/artifacts
end_time: 1743028584254
entry_point_name: ''
experiment_id: '419635633295998848'
lifecycle_stage: active
run_id: edf2848a8fcb45e591568f56edadddc0
run_name: merciful-mare-152
run_uuid: edf2848a8fcb45e591568f56edadddc0
source_name: ''
source_type: 4
source_version: ''
start_time: 1743028583950
status: 3
tags: []
user_id: Francy
