artifact_location: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848
creation_time: 1743025161973
experiment_id: '419635633295998848'
last_update_time: 1743025161973
lifecycle_stage: active
name: feedback_experiment
