artifact_uri: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/4d59fe72785a4abdb2defca8aae759d1/artifacts
end_time: 1743025739756
entry_point_name: ''
experiment_id: '419635633295998848'
lifecycle_stage: active
run_id: 4d59fe72785a4abdb2defca8aae759d1
run_name: loud-cod-357
run_uuid: 4d59fe72785a4abdb2defca8aae759d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1743025739492
status: 3
tags: []
user_id: Francy
