artifact_uri: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/95a1bf1b6fba4461969a5afba3b7dfbd/artifacts
end_time: 1743025204000
entry_point_name: ''
experiment_id: '419635633295998848'
lifecycle_stage: active
run_id: 95a1bf1b6fba4461969a5afba3b7dfbd
run_name: bright-koi-248
run_uuid: 95a1bf1b6fba4461969a5afba3b7dfbd
source_name: ''
source_type: 4
source_version: ''
start_time: 1743025169888
status: 3
tags: []
user_id: Francy
