artifact_uri: file:///C:/Users/Francy/Documents/cat_and_dog_ko-main/artifacts/419635633295998848/e0aa6f1e83ee4f8ab4de10cf8fbfca95/artifacts
end_time: 1743026180413
entry_point_name: ''
experiment_id: '419635633295998848'
lifecycle_stage: active
run_id: e0aa6f1e83ee4f8ab4de10cf8fbfca95
run_name: worried-fish-320
run_uuid: e0aa6f1e83ee4f8ab4de10cf8fbfca95
source_name: ''
source_type: 4
source_version: ''
start_time: 1743026178398
status: 3
tags: []
user_id: Francy
