name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check connection to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          command_timeout: 20m
          script_stop: true
          timeout: 60s
          script: |
            echo "Connection test successful"
            whoami
            uname -a

      - name: Deploy and Run Docker Container
        uses: appleboy/ssh-action@v0.1.10
        if: success()
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          command_timeout: 20m
          script_stop: true
          timeout: 120s
          script: |
            # echo "hello world"
            set -e
            echo "Logging into Docker Hub on the remote server..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            # echo "Testing connection..."
            # whoami
            # docker info
            
            echo "Manipulating containers..."
            docker stop cat-dog-app || true
            docker rm cat-dog-app || true
            docker rmi -f fdjeumen/cat_and_dog_ko-main-app:latest
            
            echo "Pulling new image..."
            docker pull fdjeumen/cat_and_dog_ko-main-app:latest
            
            echo "Starting new container..."
            docker run -d \
              --name cat-dog-app \
              -p 5000:5000 \
              -p 5001:5001 \
              --restart unless-stopped \
              fdjeumen/cat_and_dog_ko-main-app:latest    