name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.FAIZI_PK }}" > ./francis
          chmod 600 ./francis
          cat ./francis

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 134.199.236.159 >> ~/.ssh/known_hosts
  
      - name: Deploy and Run Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: '134.199.236.159'
          username: 'root'
          password: '123qweASD'
          # key_path: ./francis
          port: 22
          script: |
            echo "hello world"
      #       set -e
      #       echo "Testing connection..."
      #       whoami
      #       docker info
            
      #       echo "Manipulating containers..."
      #       docker stop cat-dog-app || true
      #       docker rm cat-dog-app || true
            
      #       echo "Pulling new image..."
      #       docker pull '"${DOCKER_USERNAME}"'/cat-dog-app:latest
            
      #       echo "Starting new container..."
      #       docker run -d \
      #         --name cat-dog-app \
      #         -p 5000:5000 \
      #         -p 5001:5001 \
      #         --restart unless-stopped \
      #         '"${DOCKER_USERNAME}"'/cat-dog-app:latest

            
      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     eval $(ssh-agent -s)
      #     ssh-add ~/.ssh/id_rsa
      #     ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy to Server
      #   env:
      #     SERVER_HOST: ${{ secrets.SERVER_HOST }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deploy@${SERVER_HOST} '
      #       set -e
      #       echo "Testing connection..."
      #       whoami
      #       docker info
            
      #       echo "Manipulating containers..."
      #       docker stop cat-dog-app || true
      #       docker rm cat-dog-app || true
            
      #       echo "Pulling new image..."
      #       docker pull '"${DOCKER_USERNAME}"'/cat-dog-app:latest
            
      #       echo "Starting new container..."
      #       docker run -d \
      #         --name cat-dog-app \
      #         -p 5000:5000 \
      #         -p 5001:5001 \
      #         --restart unless-stopped \
      #         '"${DOCKER_USERNAME}"'/cat-dog-app:latest
      #     '